name = "gulalai khan"
age = "23"

print(name)
print(name.upper())
print(name.lower())
print(name.find("khan"))
print(name.endswith("n"))
print(name.startswith("I"))
print(name.casefold())
print(name.count("a"))
print(name.center(30))
print(name.encode())
print(name.encode("utf7"))
print(name.encode("utf-16"))
print(name.format_map("khan"))
print(name.isidentifier())
print(name.islower())
print(name.isupper())
print(age.isspace())
print(age.isnumeric())
print(name.isalpha())
print(age.isalnum())
print(age.isalpha())
print(age.isdecimal())
print(age.isdigit())
print(name.replace("a", "t"))
print(name.title())
print(name.index("a"))
print(name.rfind("i"))
print(name.__dir__())
print(name.join("5344"))